name: Build wheels

on: [push]

env:
  MYPY_REPO: ${{ github.repository_owner }}/mypy

jobs:
  build_wheels:
    name: Build ${{ matrix.only }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            only: cp310-manylinux_x86_64
          - os: ubuntu-latest
            only: cp311-manylinux_x86_64
          - os: macos-latest
            only: cp310-macosx_x86_64
          - os: macos-latest
            only: cp311-macosx_x86_64
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Checkout mypy
        shell: bash
        run: |
          git clone https://github.com/${{ env.MYPY_REPO }}.git
          git -C mypy checkout $(cat mypy_commit)

      - uses: pypa/cibuildwheel@v2.11.1
        with:
          config-file: cibuildwheel.toml
          package-dir: mypy
          only: ${{ matrix.only }}

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./wheelhouse/*.whl

  release:
    name: create release
    needs: [build_wheels]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs').promises;
            const { repo: { owner, repo }, sha } = context;

            console.log('environment', process.versions);
            console.log({ owner, repo, sha });

            const release = await github.rest.repos.createRelease({
              owner, repo,
              // if GITHUB_REF just appears to be a branch, use tag-{commit} as the tag
              tag_name: process.env.GITHUB_REF.includes("refs/heads/") ? "tag-" + sha : process.env.GITHUB_REF.split("/").pop(),
              target_commitish: sha
            });

            console.log('created release', { release });

            for (let file of await fs.readdir('dist')) {
              console.log('uploading', file);

              await github.rest.repos.uploadReleaseAsset({
                owner, repo,
                release_id: release.data.id,
                name: file,
                data: await fs.readFile(`./dist/${file}`)
              });
