name: Create tag

on:
  workflow_dispatch:
    inputs:
      commit:
        description: Commit sha
        required: true
        type: string
  repository_dispatch:
    types: [build-wheels]

env:
  MYPY_REPO: cdce8p/mypy

jobs:
  create_tag:
    name: Create tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get commit sha
        id: get-sha
        run: |
          if [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
            sha=${{ github.event.inputs.commit }}
          elif [[ ${{ github.event_name }} == 'repository_dispatch' ]]; then
            sha=${{ github.event.client_payload.commit }}
          fi
          echo "Commit: $sha"
          echo "commit=$sha" >> $GITHUB_OUTPUT
      - name: Get mypy version
        id: mypy-version
        run: |
          sha=${{ steps.get-sha.outputs.commit }}
          git clone https://github.com/${{ env.MYPY_REPO }}
          git -C mypy checkout $sha
          if [[ $? == 1 ]]; then
            echo "Commit $sha doesn't exist"
            exit 1
          fi

          base=$(
            cat mypy/mypy/version.py | \
            grep -e ^__version__ | \
            cut -d '=' -f2 | tr -d ' "')
          if [[ $base == *"+dav" ]]; then
            version="v$base.$sha"
          else
            version="v$base"
          fi
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "Found: $version"
      - name: Check existing mypy tags
        id: mypy-wheels
        continue-on-error: true
        run: |
          tag=${{ steps.mypy-version.outputs.version }}
          echo "$tag"
          gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/mypyc/mypy_mypyc-wheels/releases/tags/$tag
          echo "found=true" >> $GITHUB_OUTPUT
      - name: Check existing custom tags
        id: custom-wheels
        continue-on-error: true
        if: steps.mypy-wheels.outputs.found != 'true'
        run: |
          tag=${{ steps.mypy-version.outputs.version }}
          echo "$tag"
          gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/releases/tags/$tag
          echo "found=true" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3.3.0
        if: |
          steps.mypy-wheels.outputs.found != 'true'
          && steps.custom-wheels.outputs.found != 'true'
        with:
          token: ${{ secrets.PUSH_TOKEN }}
      - name: Create Tag
        if: |
          steps.mypy-wheels.outputs.found != 'true'
          && steps.custom-wheels.outputs.found != 'true'
          && false
        run: |
          version=${{ steps.mypy-version.outputs.version }}
          echo "${{ steps.get-sha.outputs.commit }}" > mypy_commit
          git commit -am "Build wheels for mypy $version"
          git tag $version
          git push --tags
